INSERT INTO main_cidade (nome, estado, taxa_deslocamento, excluida) VALUES
('Bauru', 'SP', 0, false),
('Belém', 'PA', 0.2, false),
('Belo Horizonte', 'MG', 0.1, false),
('Bonito', 'MS', 0.15, false),
('Brasília', 'DF', 0.15, false),
('Campinas', 'SP', 0, false),
('Campo Grande', 'MS', 0.15, false),
('Campos de Jordão', 'SP', 0, false),
('Costa do Sauípe', 'BA', 0.2, false),
('Costão do Santinho', 'SC', 0.1, false),
('Cuiabá', 'MT', 0.15, false),
('Curitiba', 'PR', 0.1, false),
('Florianópolis', 'SC', 0.1, false),
('Fortaleza', 'CE', 0.2, false),
('Foz do Iguaçu', 'PR', 0.1, false),
('Goiânia', 'GO', 0.15, false),
('Gramado', 'RS', 0.1, false),
('Jaú', 'SP', 0, false),
('João Pessoa', 'PB', 0.2, false),
('Maceió', 'AL', 0.2, false),
('Manaus', 'AM', 0.2, false),
('Natal', 'RN', 0.2, false),
('Olinda', 'PE', 0.2, false),
('Ouro Preto', 'MG', 0.1, false),
('Porto Alegre', 'RS', 0.1, false),
('Recife', 'PE', 0.2, false),
('Ribeirão Preto', 'SP', 0, false),
('Rio de Janeiro', 'RJ', 0.1, false),
('Salvador', 'BA', 0.2, false),
('Santos', 'SP', 0, false),
('São José do Rio Preto', 'SP', 0, false),
('São Luis', 'MA', 0.2, false),
('São Paulo', 'SP', 0, false),
('Uberaba', 'MG', 0.1, false),
('Vitória', 'ES', 0.1, false),
('Rio Branco', 'AC', 0.2, false);
