# Generated by Django 4.2.13 on 2024-05-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('comida_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=400)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade_minima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComidaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.IntegerField()),
                ('comida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField()),
                ('qtd_dias_evento', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('comidas', models.ManyToManyField(through='main.ComidaEvento', to='main.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Terceiro',
            fields=[
                ('id_terceiro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='TerceiroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('id_terceiro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.terceiro')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evento')),
            ],
        ),
        migrations.CreateModel(
            name='LocalEvento',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('agravo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.localevento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='terceiros',
            field=models.ManyToManyField(through='main.TerceiroEvento', to='main.terceiro'),
        ),
        migrations.AddField(
            model_name='comidaevento',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('inscricao_estadual', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.endereco')),
                ('evento_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
            ],
        ),
    ]
