# Generated by Django 4.2.13 on 2024-10-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=300)),
                ('taxa_deslocamento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('excluida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('inscricao_estadual', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('observacao', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=100)),
                ('prazo_pagamento', models.CharField()),
                ('taxa_financeira', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('inicio_contrato', models.DateField(blank=True, null=True)),
                ('fim_contrato', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('comida_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=400)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantidade_minima', models.IntegerField()),
                ('tipo', models.CharField(max_length=200)),
                ('subtipo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_evento', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField()),
                ('qtd_dias_evento', models.IntegerField(blank=True, null=True)),
                ('qtd_pessoas', models.IntegerField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('clientes', models.ManyToManyField(to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id_logistica', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(max_length=20)),
                ('in_sp', models.BooleanField(default=True)),
                ('excluida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticaOrcamento',
            fields=[
                ('id_logistica_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField(default=1)),
                ('logistica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.logistica')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('data_alteracao', models.DateField(auto_now=True, null=True)),
                ('observacoes', models.TextField(max_length=2000)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_logisticas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_comidas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_desconto_logisticas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_desconto_comidas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_decoracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='main.cliente')),
                ('comidas', models.ManyToManyField(through='main.ComidaOrcamento', to='main.comida')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='main.evento')),
                ('logisticas', models.ManyToManyField(through='main.LogisticaOrcamento', to='main.logistica')),
            ],
        ),
        migrations.AddField(
            model_name='logisticaorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orcamento'),
        ),
        migrations.CreateModel(
            name='LogisticaCidade',
            fields=[
                ('id_logistica_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('hospedagem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('passagem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alimentacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frete_terceiros', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('frete_proprio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('frete_proprio_intervalo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('frete_proprio_completo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('diaria_completo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('diaria_simples', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('logistica_lanches', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('logistica_lanches_grande', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='LocalEvento',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('excluida', models.BooleanField(default=False)),
                ('cidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.cidade')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.localevento'),
        ),
        migrations.AddField(
            model_name='comidaorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orcamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.endereco'),
        ),
    ]
