# Generated by Django 4.2.13 on 2024-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='nome',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='comidaevento',
            name='nome',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='localevento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
