# Generated by Django 4.2.13 on 2024-07-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='clientes',
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.localevento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='clientes',
            field=models.ManyToManyField(null=True, to='main.cliente'),
        ),
    ]
