# Generated by Django 4.2.13 on 2024-06-14 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_terceiroevento_valor_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id_logistica', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dias', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Pessoa', 'Pessoa'), ('Material', 'Material')], max_length=20)),
            ],
        ),

        migrations.AddField(
            model_name='evento',
            name='logistica',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.logistica'),
        ),
    ]
