# Generated by Django 4.2.13 on 2024-07-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comidaorcamento_logisticaorcamento_orcamento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
