# Generated by Django 5.0.4 on 2024-05-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cliente_cidade_cliente_evento_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=200),
        ),
    ]
