# Generated by Django 4.2.13 on 2024-07-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_evento_clientes_alter_evento_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localevento',
            name='agravo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='taxa_financeira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
