# Generated by Django 4.2.13 on 2024-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_localevento_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
