# Generated by Django 4.2.13 on 2024-10-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cliente_observacao_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fim_contrato',
            field=models.DateField(default='2024-10-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inicio_contrato',
            field=models.DateField(default='2024-10-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
