# Generated by Django 4.2.13 on 2024-06-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_logistica_remove_terceiroevento_id_evento_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='evento',
            name='logistica',
        ),

        migrations.AddField(
            model_name='logistica',
            name='evento_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.evento'),
        ),

    ]
