# Generated by Django 4.2.13 on 2024-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cidade_id_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
    ]
