# Generated by Django 4.2.13 on 2024-06-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_terceiroevento_id_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceiroevento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='terceiroevento',
            name='id_terceiro',
        ),
        migrations.RenameField(
            model_name='logistica',
            old_name='evento_id',
            new_name='evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='terceiros',
        ),
        migrations.DeleteModel(
            name='Terceiro',
        ),
        migrations.DeleteModel(
            name='TerceiroEvento',
        ),
    ]
