# Generated by Django 4.2.13 on 2024-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orcamento_valor_desconto_comidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaorcamento',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
