# Generated by Django 5.0.4 on 2024-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cardapioupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapioupload',
            old_name='arquivo',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='cardapioupload',
            name='id',
        ),
        migrations.AddField(
            model_name='cardapioupload',
            name='id_arquivo',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardapioupload',
            name='title',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
