# Generated by Django 4.2.13 on 2024-11-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cliente_fim_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos_orcamento', to='main.orcamento')),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='descontos',
            field=models.ManyToManyField(blank=True, related_name='orcamentos', to='main.desconto'),
        ),
    ]
