# Generated by Django 4.2.13 on 2024-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cidade_excluida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prazo_pagamento',
            field=models.CharField(),
        ),
    ]
