# Generated by Django 5.0.4 on 2024-05-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_arquivo_cardapioupload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapioupload',
            name='title',
        ),
    ]
