# Generated by Django 4.2.13 on 2024-06-15 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_terceiroevento_id_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
