# Generated by Django 4.2.13 on 2024-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cliente_prazo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
    ]
