# Generated by Django 4.2.13 on 2024-08-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orcamento_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticacidade',
            name='diaria_completo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='diaria_simples',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='frete_proprio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='frete_proprio_completo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='frete_proprio_intervalo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='frete_terceiros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='logistica_lanches',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='logisticacidade',
            name='logistica_lanches_grande',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
