# Generated by Django 4.2.13 on 2024-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cliente_taxa_financeira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='data_alteracao',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
