# Generated by Django 4.2.13 on 2024-06-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_evento_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='evento_id',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='evento',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='main.evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
