# Generated by Django 5.0.4 on 2024-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cardapioupload_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapioupload',
            name='id_arquivo',
        ),
        migrations.AddField(
            model_name='cardapioupload',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
