# Generated by Django 4.2.13 on 2024-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comida_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistica',
            name='dias',
        ),
        migrations.AlterField(
            model_name='logistica',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
