# Generated by Django 4.2.13 on 2024-06-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_orcamento_evento_id_orcamento_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='evento_pk',
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente'),
            preserve_default=False,
        ),
    ]
