# Generated by Django 5.0.4 on 2024-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cardapioupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardapioUpload',
        ),
        migrations.AddField(
            model_name='comida',
            name='quantidade_minima',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
