# Generated by Django 4.2.13 on 2024-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comida_fator_multiplicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaorcamento',
            name='dias',
            field=models.IntegerField(default=1),
        ),
    ]
