# Generated by Django 4.2.13 on 2024-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_logistica_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistica',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
    ]
