# Generated by Django 4.2.13 on 2024-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orcamento_data_alteracao_orcamento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='valor_desconto_comidas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_desconto_logisticas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total_comidas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total_logisticas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
