# Generated by Django 4.2.13 on 2024-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_logisticaorcamento_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='transporte',
            field=models.CharField(default='Terceirizado', max_length=100),
        ),
    ]
