# Generated by Django 4.2.13 on 2024-08-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_orcamento_valor_desconto_comidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='subtipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
