# Generated by Django 4.2.13 on 2024-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_evento_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo_evento',
            field=models.CharField(unique=True),
        ),
    ]
