# Generated by Django 4.2.13 on 2024-07-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_frete_logisticacidade_alimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='localevento',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
    ]
