# Generated by Django 4.2.13 on 2024-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_evento_codigo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_locomocao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
