# Generated by Django 4.2.13 on 2024-08-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comida_subtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
