# Generated by Django 4.2.13 on 2024-08-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_comida_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
