# Generated by Django 4.2.13 on 2024-08-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orcamento_valor_imposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_decoracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
