# Generated by Django 4.2.13 on 2024-09-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_orcamento_valor_decoracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticaorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orcamento'),
        ),
    ]
